language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements-full.txt --use-mirrors"
  - "pip install flake8 --use-mirrors"
  - "pip install freezegun --use-mirrors"
  - "pip install . --use-mirrors"
# We run tests and afterwards nikola to see if the command is executable.
script:
  - "diff requirements.txt requirements-full.txt | grep '^<' && echo 'WARNING WARNING WARNING: Some dependencies are missing from requirements-full.txt!' || echo 'Dependency check passed!'"
  - nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE
  - nikola help
  - "flake8 --ignore=E501 ."
after_success:
  - coveralls
