language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# The dependencies we rely on are not yet full Python 3.x compatible.
#  - "3.2"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install . --use-mirrors"
# command to run tests
script: nosetests
