before_install:
- pip install --upgrade pip wheel
language: python
cache:
- apt
- pip
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
    - language-pack-pl-base
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - os: osx
    language: generic
    env: NMODE=nikola OS=macOS
    python: '3.6'
    before_install:
    - brew install python3
    - pip3 install virtualenv
    - python3 -m virtualenv nikola-tests-venv
    - source nikola-tests-venv/bin/activate
    - pip install --upgrade pip wheel
  - python: '3.6'
    env: NMODE=flake8
env:
  matrix:
  - NMODE=nikola
  global:
    secure: GqUDW0j4Ay8pS9tS/g5JBYGtgBG0g0oD2g4X9JXgVchiFj3GIRL+dwiXpgx3LELy7nCWF3EzClFxxMdVqqxizQ/I8xqiA0XL/rf5z/y+9d9nmKOxV8SV73n0eCgsHWkbdSLJ6MKs6s0Trlz9jLu/P+Bhfu2ttqkOH8WttfEf3VE=
install:
- if [[ $NMODE == 'nikola' ]]; then scripts/getwheelhouse.sh $(scripts/getpyver.py short); fi
- if [[ $NMODE == 'nikola' ]]; then pip install -r requirements-tests.txt; if [[ "$?" == '1' ]]; then cat /home/travis/.pip/pip.log; false; fi; fi
- if [[ $NMODE == 'nikola' ]]; then pip install .; fi
- if [[ $NMODE == 'flake8' ]]; then pip install flake8 pydocstyle; fi
script:
- if [[ $NMODE == 'nikola' ]]; then py.test tests/; fi
- if [[ $NMODE == 'nikola' ]]; then nikola; fi
- if [[ $NMODE == 'nikola' ]]; then nikola help; fi
- if [[ $NMODE == 'nikola' ]]; then scripts/codacy_coverage.sh; fi
- if [[ $NMODE == 'flake8' ]]; then flake8 nikola/ tests/; fi
- if [[ $NMODE == 'flake8' ]]; then pydocstyle --count --match-dir='(?!^\\.)(?!data).*' nikola/; fi
after_success:
notifications:
  irc:
    channels:
    - chat.freenode.net#nikola
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view: %{compare_url}'
    - 'Build details: %{build_url}'
    skip_join: true
    use_notice: true
