language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install flake8 --use-mirrors"
  - "pip install . --use-mirrors"
# We run tests and afterwards nikola to see if the command is executable.
script:
 - nosetests --with-doctest
 - nikola help
 - "flake8 --exit-zero nikola --ignore=E501"
