# stolen from https://github.com/jakubroztocil/httpie/blob/master/appveyor.yml
build: false
environment:
  matrix:
    - PYTHON: "C:/Python36"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
  - "set path=%PYTHON%/Scripts;%path%"
  - "%PYTHON%/python.exe --version"
  - "%PYTHON%/Scripts/pip.exe --version"

install:
  - "%PYTHON%/python.exe -m pip install --upgrade-strategy eager -U pip setuptools wheel"
  - "%PYTHON%/python.exe -m pip install --upgrade-strategy eager -Ur requirements-extras.txt pytest coverage pytest-cov mock freezegun"
  - "%PYTHON%/python.exe -m pip install ."

test_script:
  - "py.test tests/"
  - "nikola"
  - "nikola help"
