# stolen from https://github.com/jakubroztocil/httpie/blob/master/appveyor.yml
build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    #- PYTHON: "C:/Python34"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements-extras.txt pytest mock freezegun"
  - "%PYTHON%/Scripts/pip.exe install ."

test_script:
  - "set path=%PYTHON%/Scripts;%path%"
  - "%PYTHON%/python.exe --version"
  - "%PYTHON%/Scripts/pip.exe --version"
  - "py.test tests/"
  - "nikola"
  - "nikola help"
